### ISSUE TITLE
Ingest non-json output in cloudwatch

### ISSUE THREAD

**Issue by ajette** [honeycombio/agentless-integrations-for-aws#10]
Any logs that we have control over in Cloudwatch are in json, but some things inevitably get dumped into it that are not formatted. Stacktraces, etc.

Could functionality be added to ingest non-json into a specified field so that we can still search it?

**Comment by tredman** [comment]
With 1.3.0 (https://github.com/honeycombio/agentless-integrations-for-aws/pull/9) we've added an optional ErrorDataset parameter to the integration. If set, parser errors will generate some new fields, including `meta.raw_message` when can be used to see/search on the raw data if it didn't get parsed correctly as JSON. These can go to your existing dataset, or an alternative dataset (such as one with shorter retention). I think this will do what you need, can you try it and let us know if it works out?

![image](https://user-images.githubusercontent.com/3129677/44611817-785d4680-a7b8-11e8-8ea0-fd032c43ad06.png)

**Comment by ajette** [comment]
Brilliant!
