### ISSUE TITLE
Add support for configuring integrations using environment variables

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/agentless-integrations-for-aws#111]
**Is your feature request related to a problem? Please describe.**
To add flexibility when configuring integrations, it might be desirable to support configuration via environment variables.

- see #95 for more details

**Describe the solution you'd like**
Support configuring integrations using environment variables.

NOTE: Other integrations may also benefit.

**Describe alternatives you've considered**

**Additional context**

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
