### ISSUE TITLE
Document the regexps now that they're embedded in Go code

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/agentless-integrations-for-aws#159]
We just merged #150 which moved a bunch of complex regexps into the Go code, where they had previously been in human-editable strings.

We should 
* vet them for correctness (in particular, the ELB one is sketch)
* document them in more detail
* consider some level of making them more maintainable

Please see review comments on #150 for more.

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, dormant issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
