### ISSUE TITLE
Enable Travis CI build/deploy

### ISSUE THREAD

**Issue by ringods** [honeycombio/agentless-integrations-for-aws#16]
To make contributions easier without regressions, please enable Travis CI for build and deploy.

I assume the build part for Go is quite straightforward.

The deploy part is linking the following parts together:
* deploy when a new Git tag is set. Example: https://github.com/terra-farm/terraform-provider-virtualbox/blob/040fd0fec3dcc7ac6a7771662135166003871c2e/.travis.yml#L48-L50
* Use the AWS S3 deployer: https://docs.travis-ci.com/user/deployment/s3/
* Set the correct AWS region: https://docs.travis-ci.com/user/deployment/s3/#s3-bucket-regions
* Deploy to multiple buckets: https://docs.travis-ci.com/user/deployment/s3/#deploy-to-multiple-buckets

**Comment by MikeGoldsmith** [comment]
Closing as we have moved to CirceCI and do publish on tag/release.
