### ISSUE TITLE
Deploy lambdas to us-gov-west-1 and us-gov-east-1

### ISSUE THREAD

**Issue by dougireton** [honeycombio/agentless-integrations-for-aws#239]
**Is your feature request related to a problem? Please describe.**

We are using `us-gov-west-1` (AWS GovCloud). It would be nice if Honeycomb deployed these lambas to GovCloud Regions. As a workaround I have to download the lambas and upload them to a bucket we own. As a consequence I have to modify the Honeycomb-provided [CloudFormation templates](https://honeycomb-builds.s3.amazonaws.com/cloudformation-templates/latest/s3-logfile.yml) since the Lamba bucket name where the .zips live is hardcoded.

**Describe the solution you'd like**

Deploy lambdas to us-gov-west-1 and us-gov-east-1

**Describe alternatives you've considered**

See above

**Additional context**

**Comment by brookesargent** [comment]
Tracking the workaround for overriding the lambda artifact in the CloudFormation template over [here](https://github.com/honeycombio/cloudformation-integrations/issues/35) and closing this issue
