### ISSUE TITLE
ALB support

### ISSUE THREAD

**Issue by apechimp** [honeycombio/agentless-integrations-for-aws#4]
It looks like this supports ingesting ELB access logs, but not ALB access logs.

**Comment by nathanleclaire** [comment]
I'm tempted to say you should make a PR with an ALB template now that you have this working. I'm going to sync with @tredman when he gets back to see if he'd be interested.

**Comment by apechimp** [comment]
I can definitely do that. I'll make another issue tomorrow for the dynamic
sampling we discussed in slack.
