### ISSUE TITLE
Add support for CloudTrail logs

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/agentless-integrations-for-aws#75]
**Is your feature request related to a problem? Please describe.**

CloudTrail logs can be sent to S3 or CloudWatch, both of which are supported by agentless. However, that fact is not clear without proper documentation and support. Instead, it appears that honeyaws is the only option to pull CloudTrail logs into Honeycomb.

**Describe the solution you'd like**

Adding a template and documentation for using agentless to ingest CloudTrail logs to Honeycomb.

**Describe alternatives you've considered**

**Additional context**

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
