### ISSUE TITLE
De-dupe docs

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/agentless-integrations-for-aws#83]
There are currently duplicate docs in the readme and the [public docs](https://docs.honeycomb.io/getting-data-in/integrations/aws/). This makes it hard to keep them consistent. We have a [precedent](https://github.com/honeycombio/honeycomb-opentelemetry-java) of moving the majority of usage documentation to the public docs, and referencing them in the readme. We should do this here as well.

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
