### ISSUE TITLE
Allow adding fields in cloudwatch-handler

### ISSUE THREAD

**Issue by antifuchs** [honeycombio/agentless-integrations-for-aws#84]
**Is your feature request related to a problem? Please describe.**

We ingest cloudwatch-based EKS audit trails from multiple EKS instances, and would love to have a way to discern between the different clusters.

**Describe the solution you'd like**

The honeycomb k8s integration has [processors that can add fields to events](https://docs.honeycomb.io/getting-data-in/integrations/kubernetes/configuration/#additional_fields) - having something similar in the cloudwatch handler would be really cool. 

**Describe alternatives you've considered**

We could ingest these events into different datasets, I guess? Or start tagging everything with `env`, but that's not extremely expressive - especially as we need multiple labels to tell the clusters apart (purpose and region, for one).

**Additional context**

**Comment by vreynolds** [comment]
Thanks for the idea! It does sounds like a useful feature.

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
