### ISSUE TITLE
Allow API token to be pulled from SSM Secure String

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [honeycombio/agentless-integrations-for-aws#89]
**Is your feature request related to a problem? Please describe.**
If I elect to use the Honeycomb log forwarding lambda, not only can it be performed with standard AWS Terraform resources, [there are even starter code samples available for doing this](https://github.com/honeycombio/agentless-integrations-for-aws/blob/73974ef1b1e6e845a565dbbec9c5e15723a79af6/terraform/cloudwatch-logs-json.tf) in this repository, which I am very grateful for. That said, part of those instructions include instructions for optionally encrypting the API key, with the express declaration that this is recommended. Doing this requires first creating a KMS key, and then using it to generate the encrypted payload, and providing that key ID in the environment variables for the lambda. 

When designing my infrastructure, I aimed to use Terraform from start-to-finish, with no subsequent steps required for production readiness. That is to say, I want to run `terraform apply` once, and have everything taken care of when it's done. This precludes me from being able to follow these best practices, because there is no way in Terraform to generate a KMS key, and then use that key to encrypt a value. I have to encrypt the value in the command line, which inherently introduces more than one step in the terraform deploy.

**Describe the solution you'd like**
I'd like to use a `SecureString` SSM parameter instead. This way the key is still encrypted at rest, and we can use the SSM client to decrypt it upon request. I can create a KMS key to encrypt a secure string parameter AND I can set the encrypted value of that parameter with SSM SecureStrings.

**Describe alternatives you've considered**
The alternative is to abandon my ardent desire to have one stage to this deploy.

**Additional context**
I wanted to disclose that I am:

1.) I am more than happy to implement this feature myself, and have held off from doing so because the OSS guide suggested it.
2.) I am very grateful for this software and for all the efforts of those involved. It is not my intention for this request to be viewed as antagonism towards any developer responsible for the code. Thank you for all your hard work.
3.) Additionally, I am open to the idea that there is a better way to do this, and look forward to discussing the appropriate solution.

**Comment by vreynolds** [comment]
Hello @verygoodsoftwarenotvirus, thanks for the detailed write up!

It makes sense that you would want to pull the API key from SSM -- that's a pretty standard place to store such things.
Your specific pain point around Terraform is not entirely clear to me, can you help me understand what your ideal workflow would look like with the SecureString? (e.g. at which point does the plaintext API key come in -- would a human still need to manually populate that _somewhere_ safe?)

As far as implementation goes, do you anticipate this change to incur additional lambda overhead? I'm not familiar with the SSM client, perhaps this is equivalent to opening a KMS session and decrypting the cipher blob, like the lambda does today.
Another thing to consider is backwards compatibility. We prefer to make non-breaking changes where possible, so we would probably want to support both encrypted blobs and SSM parameters.

**Comment by verygoodsoftwarenotvirus** [comment]
>Your specific pain point around Terraform is not entirely clear to me, can you help me understand what your ideal workflow would look like with the SecureString? (e.g. at which point does the plaintext API key come in -- would a human still need to manually populate that somewhere safe?)

The plaintext API Key would have to be distributed to Terraform somehow, I've been doing so with variable sets in Terraform Cloud. Once there, you'd be able to have something like:

```tf
resource "aws_iam_role" "honeycomb_cloudwatch_logs" {
  name = "honeycomb-cloudwatch-logs-lambda-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_ssm_parameter" "honeycomb_api_key" {
  name  = "HONEYCOMB_API_KEY"
  type  = "SecureString"
  value = var.HONEYCOMB_API_KEY
}

resource "aws_lambda_function" "cloudwatch_logs" {
  s3_bucket        = "honeycomb-integrations-us-east-1"
  s3_key           = "agentless-integrations-for-aws/LATEST/ingest-handlers.zip"
  function_name    = "honeycomb-cloudwatch-logs-integration"
  role             = aws_iam_role.honeycomb_cloudwatch_logs.arn
  handler          = "cloudwatch-handler"
  runtime          = "go1.x"
  memory_size      = "128"

  environment {
    variables = {
      ENVIRONMENT = "changeme"
      PARSER_TYPE = "json"
      # naming things is hard
      SSM_PARAMETER_NAME = aws_ssm_parameter.honeycomb_api_key.name
      DATASET = "cloudwatch-logs"
      SAMPLE_RATE = "1"
      TIME_FIELD_FORMAT = "%s(%L)?"
      TIME_FIELD_NAME = "start_time"
    }
  }
}
```

With the variable properly configured and the appropriate code changes made, I could hypothetically run the above Terraform code *once* from a brand-new AWS account and have a functioning log forwarder, with a key that is encrypted at rest. The "once" part is the thing I sort of care about in all this. :)

From there, [the code](https://github.com/honeycombio/agentless-integrations-for-aws/blob/73974ef1b1e6e845a565dbbec9c5e15723a79af6/common/common.go) would do something like:
```go
func InitHoneycombFromEnvVars() error {
	sampleRate = 1
	if os.Getenv("SAMPLE_RATE") != "" {
		i, err := strconv.Atoi(os.Getenv("SAMPLE_RATE"))
		if err != nil {
			logrus.WithField("sample_rate", os.Getenv("SAMPLE_RATE")).
				Warn("Warning: unable to parse sample rate, falling back to 1.")
		}
		sampleRate = uint(i)
	}

	// If KMS_KEY_ID is supplied, we assume we're dealing with an encrypted key.
	kmsKeyID := os.Getenv("KMS_KEY_ID")
	if kmsKeyID != "" {
		encryptedWriteKey := os.Getenv("HONEYCOMB_WRITE_KEY")
		if encryptedWriteKey == "" {
			return fmt.Errorf("Value for KMS_KEY_ID but no value for HONEYCOMB_WRITE_KEY")
		} else {
			kmsSession := session.Must(session.NewSession(&aws.Config{
				Region: aws.String(os.Getenv("AWS_REGION")),
			}))

			config := &aws.Config{}
			svc := kms.New(kmsSession, config)
			cyphertext, err := base64.StdEncoding.DecodeString(encryptedWriteKey)
			if err != nil {
				logrus.WithError(err).
					Error("unable to decode ciphertext in write key")
				return fmt.Errorf("unable to decode ciphertext in write key")
			}
			resp, err := svc.Decrypt(&kms.DecryptInput{
				CiphertextBlob: cyphertext,
			})

			if err != nil {
				logrus.WithError(err).Error("unable to decrypt honeycomb write key")
				return fmt.Errorf("unable to decrypt honeycomb write key")
			}
			writeKey = string(resp.Plaintext)
		}
	} else f ssmParameterName := os.Getenv("SSM_PARAMETER_NAME"); ssmParameterName != "" {
		rawKey, err := ps.GetParameter(&ssm.GetParameterInput{
			Name:           aws.String(ssmParameterName),
			WithDecryption: aws.Bool(true),
		})
		if err != nil {
			panic(err)
		}
		
		writeKey = *rawKey.Parameter.Value
		if writeKey == "" {
			return fmt.Errorf("no value for HONEYCOMB_WRITE_KEY")
		}
	} else {
		writeKey = os.Getenv("HONEYCOMB_WRITE_KEY")
		if writeKey == "" {
			return fmt.Errorf("no value for HONEYCOMB_WRITE_KEY")
		}
	}

	apiHost = os.Getenv("API_HOST")
	if apiHost == "" {
		apiHost = "https://api.honeycomb.io"
	}

	dataset = os.Getenv("DATASET")
	if dataset == "" {
		dataset = "honeycomb-cloudwatch-logs"
	}

	errorDataset = os.Getenv("ERROR_DATASET")

	libhoney.UserAgentAddition = fmt.Sprintf("integrations-for-aws/%s", version)

	// Call Init to configure libhoney
	libhoney.Init(libhoney.Config{
		WriteKey:   writeKey,
		Dataset:    dataset,
		APIHost:    apiHost,
		SampleRate: sampleRate,
	})

	debug := envOrElseBool("HONEYCOMB_DEBUG", false)
	if debug {
		go readResponses(libhoney.TxResponses())
	}

	return nil
}
```

> As far as implementation goes, do you anticipate this change to incur additional lambda overhead? I'm not familiar with the SSM client, perhaps this is equivalent to opening a KMS session and decrypting the cipher blob, like the lambda does today.

I'm not the world's foremost AWS expert, but I would assume it is no more costly than the KMS decryption call.

Hope this helps, happy to elaborate further. :)

**Comment by vreynolds** [comment]
Thanks, that helps! I think this would be a reasonable enhancement. We can't make promises on our own timeline, but if you'd like to go ahead and open a PR, we'd be happy to get it over the finish line 😄

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
