### ISSUE TITLE
s3-handler doesn't provide enough configuration for ALB logs to be correctly imported

### ISSUE THREAD

**Issue by ajbouh** [honeycombio/agentless-integrations-for-aws#95]
**Is your feature request related to a problem? Please describe.**
ALB logs don't show up properly in honeycomb when you follow the instructions here: https://docs.honeycomb.io/getting-data-in/integrations/aws/aws-application-load-balancer/

There are number of issues with the events that are submitted following the official documentation:
- no valid duration field
- parsed fields interfere with whatever existing schema you have
- spans lack proper tracing fields

**Describe the solution you'd like**

I'd like to use environment variables like these to configure more reasonable behavior:

```python
{
        "PARSER_TYPE": "regex",
        # https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md
        "FIELD_NAME_ALIAS_JSON": json.encode({
            "serviceName": "aws.alb.elb",
            "name": "aws.alb.request",
            "http.user_agent": "aws.alb.user_agent",
            "http.status_code": "aws.alb.elb_status_code",
            "http.method": "aws.alb.request_method",
            "http.url": "aws.alb.request_uri",
        }),
        "TIME_FIELD_NAME": "aws.alb.request_creation_time",
        "TIME_FIELD_FORMAT": "2006-01-02T15:04:05.9999Z",
        "REQUEST_FIELD_NAME": "aws.alb.request",
        "FORCE_GUNZIP": "true",
        "HONEYCOMB_DEBUG": "true",
        "DURATION_END_FIELD_NAME": "aws.alb.time",
        "DURATION_END_FORMAT": "2006-01-02T15:04:05.9999Z",
        "AMZN_TRACE_ID_FIELD_NAME": "aws.alb.amzn_trace_id",
        "PARSED_FIELD_NAME_PREFIX": "aws.alb.",
        "REGEX_PATTERN": " ".join([
            "(?P<type>[^ ]+)",
            "(?P<time>[^ ]+)",
            "(?P<elb>[^ ]+)",
            "(?P<client>[^ ]+)",
            "(?P<target>[^ ]+)",
            "(?P<request_processing_time>[^ ]+)",
            "(?P<target_processing_time>[^ ]+)",
            "(?P<response_processing_time>[^ ]+)",
            "(?P<elb_status_code>[^ ]+)",
            "(?P<target_status_code>[^ ]+)",
            "(?P<received_bytes>[^ ]+)",
            "(?P<sent_bytes>[^ ]+)",
            '"(?P<request>[^"]+)"',
            '"(?P<user_agent>[^"]+)"',
            "(?P<ssl_cipher>[^ ]+)",
            "(?P<ssl_protocol>[^ ]+)",
            "(?P<target_group_arn>[^ ]+)",
            '"(?P<amzn_trace_id>[^"]+)"',
            '"(?P<domain_name>[^"]+)"',
            '"(?P<chosen_cert_arn>[^"]+)"',
            "(?P<matched_rule_priority>[^ ]+)",
            "(?P<request_creation_time>[^ ]+)",
            '"(?P<actions_executed>[^"]+)"',
            '"(?P<redirect_url>[^"]+)"',
            '"(?P<error_reason>[^"]+)"',
            '"(?P<target_list>[^"]+)"',
            '"(?P<target_status_code_list>[^"]+)"',
        ]),
 }

```

Here's a patch that adds support for these environment variables to the existing main branch (8f7d958ae61fedf47e9e040c3f2900536bd4cf1b): https://gist.github.com/ajbouh/462b1126e28f2755aeaf085d9b61ed17

**Comment by MikeGoldsmith** [comment]
Thank you creating the issue. We'll look into it.

**Comment by ajbouh** [comment]
I edited my original message to make the gist link to a patch more obvious.

The problem wasn't that the fields didn't work in the template, it was that the alb logs didn't properly integrate with any existing schema and didn't properly include span trace fields.

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
