### ISSUE TITLE
Verify gzip handling

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/agentless-integrations-for-aws#98]
Fallout from investigating #96 which was fixed with #97 

The `s3-handler` assumes compressed objects received from S3 are uncompressed, because the aws-sdk does that automatically when the object has correct content-encoding (gzip). With ALB access logs, the files were compressed but were missing the content-encoding, which resulted in the ALB integration not parsing anything from the log files.

Verify and potentially apply the same fix to other integrations using the `s3-handler`:

- [ ] ELB logs
- [ ] S3 bucket logs
- [ ] S3 logs JSON

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
